### ISSUE TITLE
Implement a Binary Search algorithm

### ISSUE THREAD

**Issue by m-arav** [muhasin23/Learn_March_2018#1]
### Problem Statement
Implement a binary search algorithm.

In computer science, a binary search or half-interval search algorithm finds the position of a specified input value (the search "key") within an array sorted by key value.

In each step, the algorithm compares the search key value with the key value of the middle element of the array.

If the keys match, then a matching element has been found and its index, or position, is returned.

Otherwise, if the search key is less than the middle element's key, then the algorithm repeats its action on the sub-array to the left of the middle element or, if the search key is greater, on the sub-array to the right.

If the remaining array to be searched is empty, then the key cannot be found in the array and a special "not found" indication is returned.

A binary search halves the number of items to check with each iteration, so locating an item (or determining its absence) takes logarithmic time. A binary search is a dichotomic divide and conquer search algorithm.

**Comment by muhasin23** [comment]
`# Binary_Search
# Give the number set as arguments in ascending order
#count = 0
#* numbers = ARGV
#e: t_numbers = Array.new(2,$stdin.gets.chomp.to_i)
#$stdin.gets.chomp.to_i
#for number in num>ers
#  count = count + 1
#end
#puts count
#puts set_numbers
def binary_search_normal()
  number = 0
  print "please enter the size of number set: "
  size = gets.chomp.to_i
  ary = Array.new
  print "please enter #{size} elements in ascending order:\n"
  while size > number
    ary.push(gets.chomp.to_i)
    size -= 1
  end
  #bsearch_find = ary.bsearch{|x| x >= 4}
  #puts bsearch_find
  last = ary.length - 1
  first = 0
  position = 0
  flag = false
  print "please enter the number to search:"
  search_number = gets.chomp.to_i
  while (first <= last) do
    position = first + (last - first) / 2
    if (search_number == ary[position])
      flag = true
      puts "number found in position #{position + 1}"
    end
    if search_number > ary[position]
      first = position + 1
    else
      last = position - 1
    end
  end
  if flag == false
      puts "Number not found"
  end
end
binary_search_normal()
© 2018 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
`
